### ISSUE TITLE
Support modern JDK versions by updating lombok to 1.18.10 (or newer)

### ISSUE THREAD

**Issue by fl-knix** [sisyphsu/dateparser#21]
See original Lombok issue here: https://github.com/projectlombok/lombok/issues/2790

It looks like updating to a more recent version of `lombok` will do the trick!

Personally, I use OpenJDK 17 and see the error:
```
java.lang.RuntimeException: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x4d0cbf3f) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x4d0cbf3f
```

during compilation.

Thank you for this wonderful date parsing solution!

**Comment by sisyphsu** [comment]
I have upgrade `lombok` to `1.18.22` in new deployed version `1.0.9`, please try it

**Comment by fl-knix** [comment]
Confirmed fixed, thanks!
